test:
	GITHUB_TOKEN=kazaaz:b4c576243990e8768a5aba7a91209435c5aeed4a EMAIL=DD2480BuildResults@gmail.com PASSWORD=jUwzud-gyzvyt-barge9 python3 -m unittest discover -s ./ -p '*_test.py'

doc:
	pydoc3 -b ./
	
